# Copyright (c) 2026 RSG-KH | Apache-2.0 License
"""Compile the reviewed recurrence manifest; never change translations or source events."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COLUMNS = ('id', 'titleKey', 'comparisonKey', 'type', 'month', 'day', 'waxing', 'offset',
           'duration', 'fromYear', 'throughYear', 'anniversaryBase', 'monthPolicy')


def main():
    manifest = json.loads((ROOT / 'tools/recurring-event-rules.json').read_text(encoding='utf-8'))
    rules = manifest['rules']
    assert manifest['format'] == 1 and len({r['id'] for r in rules}) == len(rules)
    lines = ['# Reviewed recurrence rules; generated by tools/build-recurring-events.py.',
             '# ' + '\t'.join(COLUMNS)]
    for rule in rules:
        assert 1800 <= rule['fromYear'] <= rule['throughYear'] <= 2200
        assert rule['type'] in ('solar', 'khmer_lunar', 'new_year_first', 'new_year_middle', 'new_year_last', 'solar_nth_weekday')
        assert 1 <= rule['duration'] <= 3
        fields = [str(rule.get(c) if rule.get(c) is not None else '') for c in COLUMNS]
        assert all('\t' not in field and '\n' not in field for field in fields)
        lines.append('\t'.join(fields))
    target = ROOT / 'app/src/main/resources/recurrence-rules.tsv'
    target.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    catalog = json.loads((ROOT / 'translations/catalog.json').read_text(encoding='utf-8'))
    entries = {e['id']: e for e in catalog['entries']}
    source_dates = {parts[0]: parts[1] for line in (ROOT / 'app/src/main/resources/calendar-events.tsv').read_text(encoding='utf-8').splitlines()
                    if line and not line.startswith('#') for parts in [line.split('\t')]}
    reference = ['# Captured source dates for recurrence regression tests; no calculated dates.']
    for rule in rules:
        for occurrence in entries[rule['comparisonKey']]['occurrences']:
            assert source_dates[occurrence['id']] == occurrence['date']
            reference.append(rule['id'] + '\t' + occurrence['date'])
    (ROOT / 'app/src/test/resources/recurrence-reference.tsv').write_text('\n'.join(reference) + '\n', encoding='utf-8', newline='\n')
    print(f'Exported {len(rules)} reviewed recurrence rules.')


if __name__ == '__main__':
    main()
