// Copyright (c) 2026 RSG-KH | Apache-2.0 License
// Development-only generator: use the compiled app classes and its pinned engine.
// See docs/reference-event-database.md for the command and required classpath.
import com.rsgkh.calendar.data.EventRepository;
import com.rsgkh.calendar.data.RecurringEvents;
import com.rsgkh.calendar.domain.KhmerCalendar;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;

class ExportEngineEventDates {
    record Occurrence(String id, LocalDate date) {}

    public static void main(String[] args) throws Exception {
        var years = EventRepository.INSTANCE.getCoveredYears();
        var captured = EventRepository.INSTANCE.getCapturedYears();
        var rows = new ArrayList<Occurrence>();
        for (int year = years.getFirst(); year <= years.getLast(); year++) {
            if (year < captured.getFirst() || year > captured.getLast()) {
                for (var event : RecurringEvents.INSTANCE.forYear(year)) {
                    rows.add(new Occurrence(event.getId(), event.getDate()));
                }
            }
            for (var date = LocalDate.of(year, 1, 1); date.getYear() == year; date = date.plusDays(1)) {
                if (KhmerCalendar.INSTANCE.fromGregorian(date).isHolyDay()) rows.add(new Occurrence("sil", date));
            }
        }
        rows.sort(Comparator.comparing(Occurrence::date).thenComparing(Occurrence::id));
        if (rows.stream().distinct().count() != rows.size()) throw new IllegalStateException("Duplicate event date");
        var output = new StringBuilder("# Engine event dates; generated by tools/ExportEngineEventDates.java.\n")
            .append("# Holy days: ").append(years.getFirst()).append('-').append(years.getLast())
            .append("; recurrences only outside captured years ").append(captured.getFirst()).append('-').append(captured.getLast()).append(".\n")
            .append("# Calculated dates, not official holiday declarations.\n# columns=id,date\n");
        for (var row : rows) output.append(row.id()).append('\t').append(row.date()).append('\n');
        Files.writeString(Path.of(args[0]), output, StandardCharsets.UTF_8);
        System.out.println("Exported " + rows.size() + " engine event dates.");
    }
}
